version: '3.8'

services:
  webhook-server:
    build: .
    container_name: bkcrm-webhook-server
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - EVOLUTION_API_URL=${EVOLUTION_API_URL:-https://press-evolution-api.jhkbgs.easypanel.host}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-429683C4C977415CAAFCCE10F7D57E11}
    env_file:
      - webhook.env
    volumes:
      - ./logs:/app/logs
    networks:
      - bkcrm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  bkcrm-network:
    driver: bridge

volumes:
  logs:
    driver: local 