version: '3.8'

services:
  bkcrm:
    build: .
    container_name: bkcrm-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bkcrm-webhook
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./webhook-evolution-complete-corrigido.cjs:/app/webhook-evolution-complete-corrigido.cjs
      - ./webhook.env:/app/webhook.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["node", "webhook-evolution-complete-corrigido.cjs"]

networks:
  default:
    name: bkcrm-network 