version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./deploy-webhook/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webhook
    networks:
      - bkcrm-network

  webhook:
    build:
      context: .
      dockerfile: webhook.dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - "4000:4000"
    networks:
      - bkcrm-network

networks:
  bkcrm-network:
    driver: bridge 