version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    ports:
      - "80:80"
    volumes:
      - ./deploy-webhook/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webhook
    networks:
      - bkcrm-network

  webhook:
    build:
      context: .
      dockerfile: webhook.dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    expose:
      - "4000"
    networks:
      - bkcrm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bkcrm-network:
    driver: bridge 