import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TicketManagement } from './TicketManagement';
import { CustomerManagement } from './customers/CustomerManagement';
import { SalesFunnel } from './SalesFunnel';
import { DepartmentDiagnostic } from './admin/DepartmentDiagnostic';
import { Dashboard } from './Dashboard';
import { ChatDemo } from '../chat/ChatDemo';
import { Loader2, MessageSquare, Filter, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';
export const MainContent = ({ selectedSector, currentView, onViewChange, isLoading, sidebarCollapsed, onOpenAddTicket }) => {
    const renderContent = () => {
        if (isLoading) {
            return (_jsx("div", { className: "flex items-center justify-center h-full", children: _jsxs("div", { className: "text-center p-8", children: [_jsxs("div", { className: "relative mb-6", children: [_jsx("div", { className: "w-16 h-16 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-2xl shadow-lg mx-auto flex items-center justify-center", children: _jsx(Loader2, { className: "w-8 h-8 animate-spin text-white" }) }), _jsx("div", { className: "absolute inset-0 rounded-2xl bg-blue-400/20 animate-ping" }), _jsx("div", { className: "absolute inset-2 rounded-xl bg-blue-400/10 animate-ping animation-delay-200" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "text-lg font-semibold text-gray-900", children: "Carregando..." }), _jsx("p", { className: "text-sm text-gray-500", children: "Preparando a melhor experi\u00EAncia para voc\u00EA" })] }), _jsxs("div", { className: "flex justify-center space-x-2 mt-4", children: [_jsx("div", { className: "w-2 h-2 bg-blue-500 rounded-full animate-bounce" }), _jsx("div", { className: "w-2 h-2 bg-blue-500 rounded-full animate-bounce animation-delay-100" }), _jsx("div", { className: "w-2 h-2 bg-blue-500 rounded-full animate-bounce animation-delay-200" })] })] }) }));
        }
        switch (currentView) {
            case 'conversas':
                return (_jsx(TicketManagement, { sector: selectedSector, onOpenAddTicket: onOpenAddTicket }));
            case 'funil':
                return _jsx(SalesFunnel, { sector: selectedSector });
            case 'clientes':
                return _jsx(CustomerManagement, {});
            case 'dashboard':
                return _jsx(Dashboard, { onViewChange: onViewChange, onOpenAddTicket: onOpenAddTicket });
            case 'produtos':
                return (_jsx("div", { className: "flex items-center justify-center h-full", children: _jsxs("div", { className: "text-center p-8 max-w-md", children: [_jsxs("div", { className: "bg-gradient-to-br from-emerald-100 via-green-50 to-teal-100 rounded-3xl p-8 mb-6 relative overflow-hidden", children: [_jsx("div", { className: "absolute top-2 right-2", children: _jsx(Sparkles, { className: "w-6 h-6 text-emerald-500 animate-pulse" }) }), _jsx(MessageSquare, { className: "w-16 h-16 text-emerald-600 mb-4 mx-auto" }), _jsx("h3", { className: "text-xl font-bold text-gray-900 mb-3", children: "Produtos" }), _jsx("p", { className: "text-gray-600 leading-relaxed", children: "Funcionalidade em desenvolvimento. Em breve voc\u00EA poder\u00E1 gerenciar todos os seus produtos aqui." })] }), _jsx("div", { className: "flex justify-center", children: _jsx("div", { className: "bg-white/80 backdrop-blur-sm px-4 py-2 rounded-full border border-emerald-200 text-emerald-700 text-sm font-medium", children: "\uD83D\uDEA7 Em breve..." }) })] }) }));
            case 'disparos':
                return (_jsx("div", { className: "flex items-center justify-center h-full", children: _jsxs("div", { className: "text-center p-8 max-w-md", children: [_jsxs("div", { className: "bg-gradient-to-br from-orange-100 via-red-50 to-pink-100 rounded-3xl p-8 mb-6 relative overflow-hidden", children: [_jsx("div", { className: "absolute top-2 right-2", children: _jsx(Sparkles, { className: "w-6 h-6 text-orange-500 animate-pulse" }) }), _jsx(MessageSquare, { className: "w-16 h-16 text-orange-600 mb-4 mx-auto" }), _jsx("h3", { className: "text-xl font-bold text-gray-900 mb-3", children: "Disparos em Massa" }), _jsx("p", { className: "text-gray-600 leading-relaxed", children: "Sistema de disparos em massa em desenvolvimento. Em breve voc\u00EA poder\u00E1 enviar mensagens para m\u00FAltiplos contatos." })] }), _jsx("div", { className: "flex justify-center", children: _jsx("div", { className: "bg-white/80 backdrop-blur-sm px-4 py-2 rounded-full border border-orange-200 text-orange-700 text-sm font-medium", children: "\uD83D\uDEA7 Em breve..." }) })] }) }));
            case 'whatsapp':
            case 'evolution-api':
                return (_jsx("div", { className: "flex items-center justify-center h-full", children: _jsxs("div", { className: "text-center p-8 max-w-md", children: [_jsxs("div", { className: "bg-gradient-to-br from-blue-100 via-indigo-50 to-purple-100 rounded-3xl p-8 mb-6 relative overflow-hidden", children: [_jsx("div", { className: "absolute top-2 right-2", children: _jsx(Sparkles, { className: "w-6 h-6 text-blue-500 animate-pulse" }) }), _jsx(MessageSquare, { className: "w-16 h-16 text-blue-600 mb-4 mx-auto" }), _jsx("h3", { className: "text-xl font-bold text-gray-900 mb-3", children: "WhatsApp Integration" }), _jsx("p", { className: "text-gray-600 leading-relaxed", children: "Integra\u00E7\u00E3o WhatsApp em desenvolvimento. Em breve voc\u00EA poder\u00E1 gerenciar suas conex\u00F5es aqui." })] }), _jsx("div", { className: "flex justify-center", children: _jsx("div", { className: "bg-white/80 backdrop-blur-sm px-4 py-2 rounded-full border border-blue-200 text-blue-700 text-sm font-medium", children: "\uD83D\uDEA7 Em breve..." }) })] }) }));
            case 'admin':
                return _jsx(DepartmentDiagnostic, {});
            case 'chat-demo':
                return _jsx(ChatDemo, {});
            default:
                return (_jsx("div", { className: "flex items-center justify-center h-full", children: _jsxs("div", { className: "text-center p-8 max-w-2xl", children: [_jsxs("div", { className: "bg-gradient-to-br from-blue-100 via-indigo-50 to-purple-100 rounded-3xl p-12 mb-8 relative overflow-hidden", children: [_jsx("div", { className: "absolute top-4 right-4", children: _jsxs("div", { className: "flex space-x-1", children: [_jsx("div", { className: "w-2 h-2 bg-blue-400 rounded-full animate-pulse" }), _jsx("div", { className: "w-2 h-2 bg-indigo-400 rounded-full animate-pulse animation-delay-100" }), _jsx("div", { className: "w-2 h-2 bg-purple-400 rounded-full animate-pulse animation-delay-200" })] }) }), _jsxs("div", { className: "relative", children: [_jsx("div", { className: "w-20 h-20 bg-gradient-to-br from-blue-600 to-purple-600 rounded-2xl mx-auto mb-6 flex items-center justify-center shadow-lg", children: _jsx(MessageSquare, { className: "w-10 h-10 text-white" }) }), _jsx("h3", { className: "text-2xl font-bold text-gray-900 mb-4", children: "Bem-vindo ao CRM Sistema" }), _jsx("p", { className: "text-gray-600 leading-relaxed text-lg", children: "Sua plataforma completa para gerenciamento de relacionamento com clientes. Selecione uma op\u00E7\u00E3o do menu para come\u00E7ar a explorar." })] })] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4", children: [_jsxs("button", { onClick: () => onViewChange('conversas'), className: "group flex items-center p-4 bg-white/80 backdrop-blur-sm rounded-2xl border border-blue-200 hover:border-blue-300 transition-all duration-200 hover:scale-105 hover:shadow-lg", children: [_jsx("div", { className: "w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center mr-4 group-hover:bg-blue-200 transition-colors", children: _jsx(MessageSquare, { className: "w-6 h-6 text-blue-600" }) }), _jsxs("div", { className: "text-left", children: [_jsx("p", { className: "font-semibold text-gray-900", children: "Conversas" }), _jsx("p", { className: "text-sm text-gray-500", children: "Gerencie tickets" })] })] }), _jsxs("button", { onClick: () => onViewChange('funil'), className: "group flex items-center p-4 bg-white/80 backdrop-blur-sm rounded-2xl border border-purple-200 hover:border-purple-300 transition-all duration-200 hover:scale-105 hover:shadow-lg", children: [_jsx("div", { className: "w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center mr-4 group-hover:bg-purple-200 transition-colors", children: _jsx(Filter, { className: "w-6 h-6 text-purple-600" }) }), _jsxs("div", { className: "text-left", children: [_jsx("p", { className: "font-semibold text-gray-900", children: "Funil" }), _jsx("p", { className: "text-sm text-gray-500", children: "Acompanhe vendas" })] })] })] })] }) }));
        }
    };
    return (_jsx("div", { className: cn('flex-1 min-h-screen transition-all duration-300 ease-out', sidebarCollapsed
            ? 'pl-[80px]' // Espaço para dock colapsado centralizado (14 * 4 + 24px margin)
            : 'pl-[296px]' // Espaço para dock expandido centralizado (64 * 4 + 40px margin)
        ), children: _jsx("div", { className: "container mx-auto p-4 sm:p-6 lg:p-8 min-h-screen", children: renderContent() }) }));
};
